services:
  - type: web
    name: mediup-frontend-backoffice
    env: static
    buildCommand: npm ci && npm run build -- --configuration production
    staticPublishPath: dist/medi-up-front
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
